# Generated by Django 3.0.2 on 2020-03-07 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('script', models.TextField()),
                ('tag', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ParamsChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('function', models.TextField()),
                ('data_type', models.CharField(max_length=50)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pipelines.Pipeline')),
            ],
        ),
        migrations.CreateModel(
            name='InOutputs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_input', models.BooleanField()),
                ('name', models.CharField(max_length=100)),
                ('function', models.TextField()),
                ('description', models.TextField()),
                ('data_type', models.CharField(max_length=50)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pipelines.Process')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessPipelineJoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pipelines.Pipeline')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pipelines.Process')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('process_id', 'pipeline_id', 'order')},
            },
        ),
    ]
