# Generated by Django 3.0.2 on 2020-01-20 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_name', models.CharField(max_length=200, verbose_name='experiment name')),
                ('date_pref', models.DateTimeField(verbose_name='date performed')),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('file_type', models.CharField(max_length=20)),
                ('file_name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('version', models.IntegerField()),
                ('comments', models.TextField()),
                ('file_path', models.FilePathField(path='/mnt/c/Users/jsilva/Documents/Projects/webomics/webomics/exp_files')),
            ],
        ),
    ]
