# Generated by Django 3.0.2 on 2020-02-01 06:37

import browse.filetools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='file_path',
            field=models.FileField(upload_to=browse.filetools.user_directory_path),
        ),
    ]
