# Generated by Django 3.0.2 on 2020-03-07 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0002_auto_20200201_0137'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentCalc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calc_name', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('file_path', models.FilePathField(path='/mnt/c/Users/jsilva/Documents/Projects/webomics/webomics/media/calcs/volcano', recursive=True)),
                ('exp_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browse.Experiment')),
            ],
        ),
        migrations.CreateModel(
            name='CalcOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('calc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browse.ExperimentCalc')),
            ],
        ),
    ]
