# Generated by Django 3.0.2 on 2020-03-07 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0003_calcoptions_experimentcalc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentcalc',
            name='file_path',
            field=models.FilePathField(max_length=500, path='/mnt/c/Users/jsilva/Documents/Projects/webomics/webomics/media/calcs/volcano', recursive=True),
        ),
    ]
